### ISSUE TITLE
老哥，写的很不错，但是有个小问题

### ISSUE THREAD

**Issue by LeoMalik** [sunweiguo/miaosha-demo#1]
博客的评论系统Gitment好像挂了，不知道是不是我的个例，最后夸一句老哥写的真的很不错，估计以后一段时间都会跟着学习了，👍

**Comment by sunweiguo** [comment]
> 博客的评论系统Gitment好像挂了，不知道是不是我的个例，最后夸一句老哥写的真的很不错，估计以后一段时间都会跟着学习了，👍

真挂了。。。应该是域名的问题，之前用的域名指向这个博客，不过经常出现无法访问的问题，所以后来又把域名给干了，但是评论的相关设置可能没改，回头改一下
